### ISSUE TITLE
The infamous stem issue

### ISSUE THREAD

**Issue by ashasoroushpoor** [SusmithKrishnan/torghost#113]
Hi
im getting this error when running on ubuntu 

`Traceback (most recent call last):
  File "torghost.py", line 11, in init torghost
    from stem import Signal
ModuleNotFoundError: No module named 'stem'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "torghost.py", line 11, in init torghost
    from stem import Signal
ModuleNotFoundError: No module named 'stem'
`
I tried to fix it for so many hours now forced reinstalled stem and requests many times i even reinstalled python changed the default version and so on i can't find where the problem is .my own python codes and stem library in or outside venv works very fine can somebody give me some insights.

**Comment by fuki960** [comment]
Same error as my first time when i did:
((( # python torghost.py --start Torghost )))
And after this error i tried this one:
((( # python3 torghost.py --start Torghost )))

**Comment by fuki960** [comment]
> Hi
> im getting this error when running on ubuntu
> 
> `Traceback (most recent call last):
> File "torghost.py", line 11, in init torghost
> from stem import Signal
> ModuleNotFoundError: No module named 'stem'
> Error in sys.excepthook:
> Traceback (most recent call last):
> File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
> from apport.fileutils import likely_packaged, get_recent_crashes
> File "/usr/lib/python3/dist-packages/apport/**init**.py", line 5, in
> from apport.report import Report
> File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in
> import apport.fileutils
> File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in
> from apport.packaging_impl import impl as packaging
> File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in
> import apt
> File "/usr/lib/python3/dist-packages/apt/**init**.py", line 23, in
> import apt_pkg
> ModuleNotFoundError: No module named 'apt_pkg'
> 
> Original exception was:
> Traceback (most recent call last):
> File "torghost.py", line 11, in init torghost
> from stem import Signal
> ModuleNotFoundError: No module named 'stem'
> `
> I tried to fix it for so many hours now forced reinstalled stem and requests many times i even reinstalled python changed the default version and so on i can't find where the problem is .my own python codes and stem library in or outside venv works very fine can somebody give me some insights.


Same error as my first time.
The problem might be this:
((( # python torghost.py --start Torghost )))
And after this error i tried this one:
((( # python3 torghost.py --start Torghost )))
And it worked for me :)
