### ISSUE TITLE
AttributeError: module 'os' has no attribute 'geteuid'

### ISSUE THREAD

**Issue by kulterryan** [SusmithKrishnan/torghost#117]
C:\Users\xxxxxx\Downloads\torghost-3.1.1>torghost.py
Traceback (most recent call last):
  File "C:\Users\aryan\Downloads\torghost-3.1.1\torghost.py", line 259, in <module>
    main()
  File "C:\Users\aryan\Downloads\torghost-3.1.1\torghost.py", line 233, in main
    check_root()
  File "C:\Users\aryan\Downloads\torghost-3.1.1\torghost.py", line 86, in check_root
    if os.geteuid() != 0:
AttributeError: module 'os' has no attribute 'geteuid'

**Comment by canbooo** [comment]
It is not available on Windows, check [this answer](https://stackoverflow.com/a/14951764) for more information.
