### ISSUE TITLE
JSON Decode Error

### ISSUE THREAD

**Issue by miPwn** [SusmithKrishnan/torghost#57]
App no longer starts - model change?

Traceback (most recent call last):
  File "torghost.py", line 238, in <module>
  File "torghost.py", line 226, in main
  File "torghost.py", line 104, in start_torghost
IOError: [Errno 13] Permission denied: '/etc/tor/torghostrc'
[10262] Failed to execute script torghost

**Comment by Moh3n1384** [comment]
use this command:
sudo torghost -s

**Comment by miPwn** [comment]
It's already running as su

**Comment by miPwn** [comment]
![IMG_20200214_145612](https://user-images.githubusercontent.com/578620/74541811-38ed6180-4f3a-11ea-8a05-0438339ac11c.jpg)

**Comment by gmkbenjamin** [comment]
Fixed in 3d1541bd64fa58c72038e81ea895b9990adc4cb2
