### ISSUE TITLE
update and start error 

### ISSUE THREAD

**Issue by peterchanppp** [SusmithKrishnan/torghost#61]
sudo torghost -s
[03:11:53] Checking for update...
Traceback (most recent call last):
  File "torghost.py", line 232, in <module>
    check_update()   
  File "torghost.py", line 222, in main
    for (o, a) in opts:
  File "torghost.py", line 107, in start_torghost
    print bcolors.GREEN + '[done]' + bcolors.ENDC
  File "torghost.py", line 202, in check_update
    if choice in yes:
  File "dist-packages/requests/models.py", line 897, in json
  File "dist-packages/simplejson/__init__.py", line 518, in loads
  File "dist-packages/simplejson/decoder.py", line 370, in decode
  File "dist-packages/simplejson/decoder.py", line 400, in raw_decode
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2113] Failed to execute script torghost

**Comment by Spyelite** [comment]
i experience the same error as above

**Comment by datboigpc** [comment]
You can always Comment the check_update() on main() (line 215) of torghosts.py to bypass this.
Isnt a fix but at least you can use it.

Cheers

**Comment by gmkbenjamin** [comment]
Looks like the update server is down. Check out the latest version, it doesn't seem to force update at start.

**Comment by SusmithKrishnan** [comment]
Latest update in an NPM package crashed the entire server. Its up now!
