### ISSUE TITLE
Error torghost not working

### ISSUE THREAD

**Issue by anandpandey786** [SusmithKrishnan/torghost#62]
root@kaali:~# torghost --start
[14:26:00] Checking for update...
Traceback (most recent call last):
  File "torghost.py", line 232, in <module>
  File "torghost.py", line 222, in main
  File "torghost.py", line 107, in start_torghost
  File "torghost.py", line 202, in check_update
  File "dist-packages/requests/models.py", line 897, in json
  File "dist-packages/simplejson/__init__.py", line 518, in loads
  File "dist-packages/simplejson/decoder.py", line 370, in decode
  File "dist-packages/simplejson/decoder.py", line 400, in raw_decode
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[5597] Failed to execute script torghost

**Comment by gmkbenjamin** [comment]
try "torghost -s" 
Looks like it's not accpeting --start for some reason.

**Comment by SusmithKrishnan** [comment]
An error in NPM dependency crashed the server, Its working now
