### ISSUE TITLE
Stuck in fetching current ip

### ISSUE THREAD

**Issue by Loloman2** [SusmithKrishnan/torghost#72]
Once I start it it get stuck on Fetching Current IP...

**Comment by NandanDesai** [comment]
Check out if [this fork](https://github.com/databurn-in/TorGhost) works for you or not.

**Comment by Loloman2** [comment]
Traceback (most recent call last):
  File "torghost.py", line 117, in <module>
    notify2.init("TorGhost")
  File "notify2.py", line 103, in init
  File "dist-packages/dbus/bus.py", line 241, in get_object
  File "dist-packages/dbus/proxies.py", line 248, in __init__
  File "dist-packages/dbus/bus.py", line 180, in activate_name_owner
  File "dist-packages/dbus/bus.py", line 278, in start_service_by_name
  File "dist-packages/dbus/connection.py", line 651, in call_blocking
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
[7625] Failed to execute script torghost

**Comment by NandanDesai** [comment]
Can you open an issue my repository please? We'll take it from there

**Comment by Loloman2** [comment]
> Can you open an issue in my repository please? We'll take it from there

Tried before but it doesnt show me the option for it :(

**Comment by NandanDesai** [comment]
Enabled it. Now try
