### ISSUE TITLE
[6821] Failed to execute script torghost

### ISSUE THREAD

**Issue by asa-masterson** [SusmithKrishnan/torghost#82]
pi@raspberrypi:~/torghost $ sudo torghost -s
[22:35:31] Always check for updates using -u option
[22:35:31] Torrc file already configured
[22:35:31] DNS resolv.conf file already configured
('[22:35:31] Stopping tor service ',)
[done]
('[22:35:31] Starting new tor daemon ',)
[done]
('[22:35:31] setting up iptables rules',)
Traceback (most recent call last):
  File "torghost.py", line 257, in <module>
    main()
  File "torghost.py", line 245, in main
    start_torghost()
  File "torghost.py", line 160, in start_torghost
    % subprocess.getoutput('id -ur debian-tor')
AttributeError: 'module' object has no attribute 'getoutput'
[6821] Failed to execute script torghost

**Comment by SkyBoltDom** [comment]
what os?

**Comment by SkyBoltDom** [comment]
make sure you are using python3. Also, I have done some research and I think it is a git-package conflict error. Try taking the debian package from torghost-master and install it that way. I am not sure if you have a graphical interface on your raspberrypi but that should avoid the conflict.
