### ISSUE TITLE
Torghost JSON Decode error

### ISSUE THREAD

**Issue by smilingtearz** [SusmithKrishnan/torghost#91]
Getting the following error.
I have tried.
1. completely removing and reinstalling the package
2. updated and upgraded all packages through apt-get update & upgrade.
3. tor is installed

`root@kali:/home/kali/torghost# torghost
[17:49:10] Checking for update...
Traceback (most recent call last):
  File "torghost.py", line 232, in <module>
    if len(sys.argv) <= 1:
  File "torghost.py", line 211, in main
    print(t() + ' Your current TorGhost version : ' + bcolors.GREEN + VERSION + bcolors.ENDC)
  File "torghost.py", line 202, in check_update
    print(t() + ' CURRENT IP : ' + bcolors.GREEN + ip() + bcolors.ENDC)
  File "dist-packages/requests/models.py", line 897, in json
  File "dist-packages/simplejson/__init__.py", line 518, in loads
  File "dist-packages/simplejson/decoder.py", line 370, in decode
  File "dist-packages/simplejson/decoder.py", line 400, in raw_decode
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[43651] Failed to execute script torghost
`

**Comment by hellrider9** [comment]
Yeah same happening with me. Earlier it used to work perfectly but not running now.
If I execute torghost.py, then it is working but the torghost binary is not working.
![Screenshot from 2020-09-01 02-29-24](https://user-images.githubusercontent.com/56410386/91768518-585c8b00-ebfb-11ea-9281-4d9c8af8ead7.png)
