### ISSUE TITLE
Permission denied: '/etc/tor/torghostrc'

### ISSUE THREAD

**Issue by taseentanvir** [SusmithKrishnan/torghost#95]
### When I run the command "torghost -s", it immediately throws the error. Here's the output given below.

`[20:39:15] Checking for update...
[20:39:16] New update available please check https://github.com/SusmithKrishnan/torghost
Traceback (most recent call last):
  File "torghost.py", line 232, in <module>
    if len(sys.argv) <= 1:
  File "torghost.py", line 222, in main
    elif choice in no:
  File "torghost.py", line 112, in start_torghost
    print(t() + ' Torrc file already configured')
IOError: [Errno 13] Permission denied: '/etc/tor/torghostrc'
[115] Failed to execute script torghost`

**Comment by 1UC1F3R616** [comment]
@taseentanvir say the magical word sudo, try reinstall as sudo.
