### ISSUE TITLE
I have a problem when try to run Torghost script...please have a look at error below

### ISSUE THREAD

**Issue by hzupanc** [SusmithKrishnan/torghost#97]
u-5@u-laptop:~/Downloads/Torghost/torghost$ sudo torghost --start
[22:46:30] Checking for update...
Traceback (most recent call last):
  File "torghost.py", line 232, in <module>
    if len(sys.argv) <= 1:
  File "torghost.py", line 222, in main
    elif choice in no:
  File "torghost.py", line 107, in start_torghost
    
  File "torghost.py", line 202, in check_update
    print(t() + ' CURRENT IP : ' + bcolors.GREEN + ip() + bcolors.ENDC)
  File "dist-packages/requests/models.py", line 897, in json
  File "dist-packages/simplejson/__init__.py", line 518, in loads
  File "dist-packages/simplejson/decoder.py", line 370, in decode
  File "dist-packages/simplejson/decoder.py", line 400, in raw_decode
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[21066] Failed to execute script torghost

**Comment by 1UC1F3R616** [comment]
@hzupanc ur OS? try installing with `sudo ./build.sh` and then to run `sudo torghost -s`

**Comment by hzupanc** [comment]
@1UC1F3R616 - Sometimes script is running fine and something I got error messages as described before. 
Right now script is running...I didn't make any upgrade or something...strange...and yes I am using "Ubuntu 19.10". Thank you for reply...cheers.
